/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import javax.swing.*;
import  java.awt.*;
import UI.QuanLyTaiKhoanform;
import java.awt.Color;
import javax.swing.*;
import Model.DoiTuongNhanVien;
import Model.DoiTuongTaiKhoanDangNhap;


import UI.DangNhap;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import Model.DoiTuongNhanVien;

import java.util.*;
import Model.DoiTuongTaiKhoanDangNhap;
import Model.TaiKhoan;
import Model.NhanVien;

import controller.TaiKhoan_ctrl;
import javax.swing.table.TableRowSorter;
import controller.MaGG_ctrl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.MaKhuyenMai;
import controller.HoaDon_ctrl;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Model.HoaDon;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form Home
     */
    MaGG_ctrl gG_ctrl;
    DefaultTableModel defaultTableModel;
    public Home() {
        initComponents();
        hienthi();//Khuyen Mai
        showHoaDon();//hoadon
        
        gG_ctrl = new MaGG_ctrl();
        //tạo 1 đối tương table
        defaultTableModel  = new DefaultTableModel(){
            @Override //ko cho phép chỉnh sửa trên bảng
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        //add các cột vào
        defaultTableModel.addColumn("MaKM");
        defaultTableModel.addColumn("TenKM");
        defaultTableModel.addColumn("TyLeKM");
        
        KM_table.setModel(defaultTableModel);
        
        
        ListAllKM(gG_ctrl.getAllLMaGG());
        //end
        
    }
    private void ListAllKM(List<MaKhuyenMai> khuyenMais){
        for(MaKhuyenMai khuyenMai : khuyenMais){
            defaultTableModel.addRow(new Object[]{khuyenMai.getMaKM(), khuyenMai.getTenKM(), khuyenMai.getTyLeKM()});
        }
    }
    
    
    public  void hienthi()
    {
    
        NhanVien nv = new NhanVien();
        TaiKhoan tk = new TaiKhoan();
        
        TaiKhoan_ctrl.showtaikhoan(DangNhap.MaNV, nv, tk);
        lb_matk.setText(tk.getMatK());
        lb_tentk.setText(tk.getTenTK());
        lb_hoten.setText(nv.getHoTenNV());
        lb_gioitinh.setText(nv.getGioiTinh());
        lb_ngaysinh.setText(nv.getNgaySinh());
        lb_sdt.setText(nv.getSDT());
    
    }
    public void showHoaDon() {
        ArrayList<HoaDon> list = HoaDon_ctrl.getAllHoaDon();
        model = (DefaultTableModel) Table_hoadon2.getModel();
      
        Object[] row = new Object[7];
        for(int i=0;i< list.size();i++){
            row[0]=list.get(i).getSoHD();           
            row[1]=list.get(i).getMaNV();
            row[2]=list.get(i).getMaTV();
            row[3]=list.get(i).getNgayHD();
            row[4]=list.get(i).getTongTien();
            row[5]=list.get(i).getMaKM();
            row[6]=list.get(i).getDtl();
           
            model.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hide = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_exit = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        panel_dong = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tabquanly = new javax.swing.JTabbedPane();
        trangchuthem = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        bt_datve5 = new javax.swing.JButton();
        bt_sanpham5 = new javax.swing.JButton();
        bt_lichchieu5 = new javax.swing.JButton();
        bt_loaiphim5 = new javax.swing.JButton();
        bt_phim5 = new javax.swing.JButton();
        bt_thanhvien5 = new javax.swing.JButton();
        taikhoanthem = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb_tentk = new javax.swing.JLabel();
        lb_hoten = new javax.swing.JLabel();
        lb_gioitinh = new javax.swing.JLabel();
        lb_ngaysinh = new javax.swing.JLabel();
        lb_sdt = new javax.swing.JLabel();
        lb_matk = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        hoadonthem = new javax.swing.JPanel();
        panel_hoadon = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Table_hoadon2 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        khuyenmaithem = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tf_timkiem = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        KM_table = new javax.swing.JTable();
        bt_sualp = new javax.swing.JButton();
        bt_xoalp = new javax.swing.JButton();
        bt_themlp = new javax.swing.JButton();
        bt_tailai = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        baocaothem = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        slidemenu = new javax.swing.JPanel();
        bt_taikhoan5 = new javax.swing.JButton();
        bt_hoadon5 = new javax.swing.JButton();
        bt_khuyenmai5 = new javax.swing.JButton();
        bt_baocao5 = new javax.swing.JButton();
        bt_dangxuat5 = new javax.swing.JButton();
        bt_nhanvien5 = new javax.swing.JButton();
        bt_trangchu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hide.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report/LoGo_Emporor.png"))); // NOI18N

        panel_exit.setBackground(new java.awt.Color(51, 51, 51));
        panel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_exitMouseExited(evt);
            }
        });
        panel_exit.setLayout(null);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("X");
        panel_exit.add(jLabel12);
        jLabel12.setBounds(0, 10, 30, 20);

        panel_dong.setBackground(new java.awt.Color(51, 51, 51));
        panel_dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_dongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_dongMouseExited(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("_");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panel_dongLayout = new javax.swing.GroupLayout(panel_dong);
        panel_dong.setLayout(panel_dongLayout);
        panel_dongLayout.setHorizontalGroup(
            panel_dongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );
        panel_dongLayout.setVerticalGroup(
            panel_dongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dongLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout hideLayout = new javax.swing.GroupLayout(hide);
        hide.setLayout(hideLayout);
        hideLayout.setHorizontalGroup(
            hideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hideLayout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addComponent(panel_dong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        hideLayout.setVerticalGroup(
            hideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hideLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(hideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_dong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(hideLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 190));

        tabquanly.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        home.setBackground(new java.awt.Color(153, 153, 153));
        home.setPreferredSize(new java.awt.Dimension(790, 580));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_datve5.setBackground(new java.awt.Color(241, 242, 146));
        bt_datve5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        bt_datve5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/tickets.png"))); // NOI18N
        bt_datve5.setText("Đặt Vé");
        bt_datve5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_datve5ActionPerformed(evt);
            }
        });
        home.add(bt_datve5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 310, -1));

        bt_sanpham5.setBackground(new java.awt.Color(241, 242, 146));
        bt_sanpham5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        bt_sanpham5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/combo.png"))); // NOI18N
        bt_sanpham5.setText("Sản Phẩm");
        bt_sanpham5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sanpham5bt_sanphamActionPerformed(evt);
            }
        });
        home.add(bt_sanpham5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 309, -1));

        bt_lichchieu5.setBackground(new java.awt.Color(241, 242, 146));
        bt_lichchieu5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        bt_lichchieu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/calendar.png"))); // NOI18N
        bt_lichchieu5.setText("Lịch Chiếu");
        bt_lichchieu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_lichchieu5bt_lichchieuActionPerformed(evt);
            }
        });
        home.add(bt_lichchieu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        bt_loaiphim5.setBackground(new java.awt.Color(241, 242, 146));
        bt_loaiphim5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        bt_loaiphim5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/film-roll.png"))); // NOI18N
        bt_loaiphim5.setText("Loại Phim");
        bt_loaiphim5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loaiphim5bt_loaiphimActionPerformed(evt);
            }
        });
        home.add(bt_loaiphim5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 309, -1));

        bt_phim5.setBackground(new java.awt.Color(241, 242, 146));
        bt_phim5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        bt_phim5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/movie.png"))); // NOI18N
        bt_phim5.setText("Phim");
        bt_phim5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_phim5ActionPerformed(evt);
            }
        });
        home.add(bt_phim5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 309, -1));

        bt_thanhvien5.setBackground(new java.awt.Color(241, 242, 146));
        bt_thanhvien5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        bt_thanhvien5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/thanhvien.png"))); // NOI18N
        bt_thanhvien5.setText("Thành Viên");
        bt_thanhvien5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_thanhvien5bt_thanhvienActionPerformed(evt);
            }
        });
        home.add(bt_thanhvien5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        javax.swing.GroupLayout trangchuthemLayout = new javax.swing.GroupLayout(trangchuthem);
        trangchuthem.setLayout(trangchuthemLayout);
        trangchuthemLayout.setHorizontalGroup(
            trangchuthemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangchuthemLayout.createSequentialGroup()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        trangchuthemLayout.setVerticalGroup(
            trangchuthemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        tabquanly.addTab("tab1", trangchuthem);

        taikhoanthem.setPreferredSize(new java.awt.Dimension(861, 617));

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setForeground(new java.awt.Color(51, 51, 51));
        jPanel9.setPreferredSize(new java.awt.Dimension(790, 580));
        jPanel9.setRequestFocusEnabled(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã Tài Khoản");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 182, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tên tài khoản");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 223, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Họ Tên");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 303, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Giới Tính");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 343, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ngày Sinh");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 392, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số Điện Thoại");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 444, -1, -1));

        lb_tentk.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        lb_tentk.setForeground(new java.awt.Color(255, 255, 153));
        lb_tentk.setText("jLabel7");
        jPanel9.add(lb_tentk, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 200, -1));

        lb_hoten.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        lb_hoten.setForeground(new java.awt.Color(255, 255, 153));
        lb_hoten.setText("jLabel7");
        jPanel9.add(lb_hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 303, 200, -1));

        lb_gioitinh.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        lb_gioitinh.setForeground(new java.awt.Color(255, 255, 153));
        lb_gioitinh.setText("jLabel7");
        jPanel9.add(lb_gioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 220, -1));

        lb_ngaysinh.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        lb_ngaysinh.setForeground(new java.awt.Color(255, 255, 153));
        lb_ngaysinh.setText("jLabel7");
        jPanel9.add(lb_ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 392, 230, -1));

        lb_sdt.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        lb_sdt.setForeground(new java.awt.Color(255, 255, 153));
        lb_sdt.setText("jLabel7");
        jPanel9.add(lb_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 210, -1));

        lb_matk.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        lb_matk.setForeground(new java.awt.Color(255, 255, 153));
        lb_matk.setText("jLabel7");
        jPanel9.add(lb_matk, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 200, -1));

        jLabel21.setText("______________________________________________________");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 261, 382, -1));

        jLabel9.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Thông tin tài khoản");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 128, 280, -1));

        jLabel10.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 153));
        jLabel10.setText("Quản lý tài khoản");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, 49));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/secure.png"))); // NOI18N
        jButton2.setText("Đổi mật khẩu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        javax.swing.GroupLayout taikhoanthemLayout = new javax.swing.GroupLayout(taikhoanthem);
        taikhoanthem.setLayout(taikhoanthemLayout);
        taikhoanthemLayout.setHorizontalGroup(
            taikhoanthemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taikhoanthemLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        taikhoanthemLayout.setVerticalGroup(
            taikhoanthemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        tabquanly.addTab("tab2", taikhoanthem);

        panel_hoadon.setBackground(new java.awt.Color(51, 51, 51));
        panel_hoadon.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        jLabel17.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("QUẢN LÝ HOÁ ĐƠN");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel17)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panel_hoadon.add(jPanel7);
        jPanel7.setBounds(0, 0, 820, 110);

        jPanel19.setBackground(new java.awt.Color(51, 51, 51));

        Table_hoadon2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_hoadon2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số HD", "Mã NV", "Mã TV", "Ngày HD", "Tổng tiền", "Mã Khuyến Mãi", "Điểm trừ Tích luỹ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(Table_hoadon2);

        jButton7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton7.setText("Chỉnh Sửa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton8.setText("Tải lại");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel65.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Nhập thông tin tra cứu hoá đơn:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton12.setText("Xoá");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel65)
                        .addGap(60, 60, 60)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_hoadon.add(jPanel19);
        jPanel19.setBounds(0, 110, 820, 500);

        javax.swing.GroupLayout hoadonthemLayout = new javax.swing.GroupLayout(hoadonthem);
        hoadonthem.setLayout(hoadonthemLayout);
        hoadonthemLayout.setHorizontalGroup(
            hoadonthemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoadonthemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_hoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hoadonthemLayout.setVerticalGroup(
            hoadonthemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_hoadon, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        tabquanly.addTab("tab3", hoadonthem);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_timkiem.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tf_timkiem.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_timkiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_timkiemActionPerformed(evt);
            }
        });
        jPanel4.add(tf_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 342, 38));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Nhập thông tin tra cứu khuyến mãi:");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, 38));

        KM_table.setAutoCreateRowSorter(true);
        KM_table.setBackground(new java.awt.Color(153, 153, 153));
        KM_table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KM_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khuyến Mãi", "Tên Khuyến Mãi", "Tỷ lệ Khuyến Mãi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        KM_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        KM_table.setCellSelectionEnabled(true);
        KM_table.setSelectionBackground(new java.awt.Color(122, 72, 221));
        KM_table.setShowGrid(true);
        KM_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(KM_table);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 174, 820, 360));

        bt_sualp.setBackground(new java.awt.Color(153, 153, 153));
        bt_sualp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bt_sualp.setForeground(new java.awt.Color(255, 255, 255));
        bt_sualp.setText("Sửa Khuyến Mãi");
        bt_sualp.setAlignmentX(0.5F);
        bt_sualp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_sualp.setMaximumSize(new java.awt.Dimension(130, 30));
        bt_sualp.setMinimumSize(new java.awt.Dimension(130, 30));
        bt_sualp.setPreferredSize(new java.awt.Dimension(130, 30));
        bt_sualp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sualpActionPerformed(evt);
            }
        });
        jPanel4.add(bt_sualp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 150, 40));

        bt_xoalp.setBackground(new java.awt.Color(153, 153, 153));
        bt_xoalp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bt_xoalp.setForeground(new java.awt.Color(255, 255, 255));
        bt_xoalp.setText("Xoá Khuyến Mãi");
        bt_xoalp.setAlignmentX(0.5F);
        bt_xoalp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_xoalp.setPreferredSize(new java.awt.Dimension(130, 30));
        bt_xoalp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoalpActionPerformed(evt);
            }
        });
        jPanel4.add(bt_xoalp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 150, 40));

        bt_themlp.setBackground(new java.awt.Color(153, 153, 153));
        bt_themlp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bt_themlp.setForeground(new java.awt.Color(255, 255, 255));
        bt_themlp.setText("Thêm Khuyến Mãi");
        bt_themlp.setAlignmentX(0.5F);
        bt_themlp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_themlp.setMaximumSize(new java.awt.Dimension(130, 30));
        bt_themlp.setMinimumSize(new java.awt.Dimension(130, 30));
        bt_themlp.setPreferredSize(new java.awt.Dimension(130, 30));
        bt_themlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themlpActionPerformed(evt);
            }
        });
        jPanel4.add(bt_themlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 150, 40));

        bt_tailai.setBackground(new java.awt.Color(153, 153, 153));
        bt_tailai.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bt_tailai.setForeground(new java.awt.Color(255, 255, 255));
        bt_tailai.setText("Tải Lại");
        bt_tailai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tailaiActionPerformed(evt);
            }
        });
        jPanel4.add(bt_tailai, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 73, 30));

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));

        jLabel18.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("QUẢN LÝ KHUYẾN MÃI");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel18)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 110));

        javax.swing.GroupLayout khuyenmaithemLayout = new javax.swing.GroupLayout(khuyenmaithem);
        khuyenmaithem.setLayout(khuyenmaithemLayout);
        khuyenmaithemLayout.setHorizontalGroup(
            khuyenmaithemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khuyenmaithemLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        khuyenmaithemLayout.setVerticalGroup(
            khuyenmaithemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        tabquanly.addTab("tab5", khuyenmaithem);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout baocaothemLayout = new javax.swing.GroupLayout(baocaothem);
        baocaothem.setLayout(baocaothemLayout);
        baocaothemLayout.setHorizontalGroup(
            baocaothemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        baocaothemLayout.setVerticalGroup(
            baocaothemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        tabquanly.addTab("tab6", baocaothem);

        getContentPane().add(tabquanly, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 820, 660));

        slidemenu.setBackground(new java.awt.Color(102, 102, 102));

        bt_taikhoan5.setBackground(new java.awt.Color(241, 242, 146));
        bt_taikhoan5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_taikhoan5.setForeground(new java.awt.Color(9, 120, 148));
        bt_taikhoan5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/profile.png"))); // NOI18N
        bt_taikhoan5.setText("Tài Khoản");
        bt_taikhoan5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt_taikhoan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_taikhoan5bt_taikhoanActionPerformed(evt);
            }
        });

        bt_hoadon5.setBackground(new java.awt.Color(241, 242, 146));
        bt_hoadon5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_hoadon5.setForeground(new java.awt.Color(9, 120, 148));
        bt_hoadon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/invoice.png"))); // NOI18N
        bt_hoadon5.setText("Hóa Đơn");
        bt_hoadon5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hoadon5ActionPerformed(evt);
            }
        });

        bt_khuyenmai5.setBackground(new java.awt.Color(241, 242, 146));
        bt_khuyenmai5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_khuyenmai5.setForeground(new java.awt.Color(9, 120, 148));
        bt_khuyenmai5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/promotion.png"))); // NOI18N
        bt_khuyenmai5.setText("Khuyến Mãi");
        bt_khuyenmai5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_khuyenmai5bt_khuyenmaiActionPerformed(evt);
            }
        });

        bt_baocao5.setBackground(new java.awt.Color(241, 242, 146));
        bt_baocao5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_baocao5.setForeground(new java.awt.Color(9, 120, 148));
        bt_baocao5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/monitor.png"))); // NOI18N
        bt_baocao5.setText("Báo Cáo");
        bt_baocao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_baocao5ActionPerformed(evt);
            }
        });

        bt_dangxuat5.setBackground(new java.awt.Color(241, 242, 146));
        bt_dangxuat5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_dangxuat5.setForeground(new java.awt.Color(9, 120, 148));
        bt_dangxuat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/exit-door.png"))); // NOI18N
        bt_dangxuat5.setText("Đăng Xuất");
        bt_dangxuat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dangxuat5ActionPerformed(evt);
            }
        });

        bt_nhanvien5.setBackground(new java.awt.Color(241, 242, 146));
        bt_nhanvien5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_nhanvien5.setForeground(new java.awt.Color(9, 120, 148));
        bt_nhanvien5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/man.png"))); // NOI18N
        bt_nhanvien5.setText("Nhân Viên");
        bt_nhanvien5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nhanvien5bt_nhanvienActionPerformed(evt);
            }
        });

        bt_trangchu.setBackground(new java.awt.Color(241, 242, 146));
        bt_trangchu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt_trangchu.setForeground(new java.awt.Color(9, 120, 148));
        bt_trangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/smarthome.png"))); // NOI18N
        bt_trangchu.setText("Trang Chủ");
        bt_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_trangchuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout slidemenuLayout = new javax.swing.GroupLayout(slidemenu);
        slidemenu.setLayout(slidemenuLayout);
        slidemenuLayout.setHorizontalGroup(
            slidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slidemenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(slidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_baocao5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_khuyenmai5, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(bt_nhanvien5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_hoadon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_taikhoan5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_trangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_dangxuat5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        slidemenuLayout.setVerticalGroup(
            slidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slidemenuLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(bt_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_taikhoan5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_nhanvien5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_hoadon5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_khuyenmai5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_baocao5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_dangxuat5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        getContentPane().add(slidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int x = 199;
    int a = 0;
    private void bt_taikhoan5bt_taikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_taikhoan5bt_taikhoanActionPerformed
        tabquanly.setSelectedIndex(1);
    }//GEN-LAST:event_bt_taikhoan5bt_taikhoanActionPerformed

    private void bt_khuyenmai5bt_khuyenmaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_khuyenmai5bt_khuyenmaiActionPerformed
        tabquanly.setSelectedIndex(3);
    }//GEN-LAST:event_bt_khuyenmai5bt_khuyenmaiActionPerformed

    private void bt_nhanvien5bt_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nhanvien5bt_nhanvienActionPerformed
        //new QuanLyNhanVienform().setVisible(true);
        //jTabbedPane1.setSelectedIndex(2);
        new QLNhanVien().setVisible(true);
    }//GEN-LAST:event_bt_nhanvien5bt_nhanvienActionPerformed

    private void bt_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_trangchuActionPerformed
        tabquanly.setSelectedIndex(0);
    }//GEN-LAST:event_bt_trangchuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new doimatkhauform().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tf_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_timkiemActionPerformed

    private void bt_sualpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sualpActionPerformed
        // TODO add your handling code here:
        int row = KM_table.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Chon loai phim can sua truoc", "Loi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String malp = String.valueOf(KM_table.getValueAt(row, 0));

            new SuaKM(malp).setVisible(true); // chuyen sang frame chinh sua loai phim
            this.dispose(); //an frame cu~ di
        }

    }//GEN-LAST:event_bt_sualpActionPerformed

    private void bt_xoalpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoalpActionPerformed
        // TODO add your handling code here:
        MaGG_ctrl maGG_ctrl = new MaGG_ctrl();
        int row = KM_table.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Vui long chon loai phim can xoa", "Loi",JOptionPane.ERROR_MESSAGE);
        }
        else{
            int confirm = JOptionPane.showConfirmDialog(null, "Ban chac chan muon xoa khong?","Xac Nhan",JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION){
                String malp = String.valueOf(KM_table.getValueAt(row, 0)); //row: hàng đã chọn, 0 là cột đầu tiền trong hàng(mã lp)
                //lphim_service.XoaLP(malp);
                maGG_ctrl.XoaKM(malp);
                defaultTableModel.setRowCount(0);
                ListAllKM(maGG_ctrl.getAllLMaGG());
            }
        }
    }//GEN-LAST:event_bt_xoalpActionPerformed

    private void bt_themlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themlpActionPerformed
        // TODO add your handling code here:
        new ThemmoiKM().setVisible(true); //chuyển sang frame thêm mới loại phim
        this.dispose(); //ẩn frame loại phim đi
    }//GEN-LAST:event_bt_themlpActionPerformed

    private void bt_tailaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tailaiActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        MaKhuyenMai khuyenMai;
        //ListAllLP(lphim_service.getAllMaKhuyenMai());

        if(tf_timkiem.getText().equals("")){
            ListAllKM(gG_ctrl.getAllLMaGG());
        }
        else {
            khuyenMai = gG_ctrl.getKM(tf_timkiem.getText());
            if(khuyenMai != null){
                defaultTableModel.addRow(new Object[]{khuyenMai.getMaKM(),khuyenMai.getTenKM(),khuyenMai.getTyLeKM()});
            }
            else JOptionPane.showMessageDialog(this,"Khong tim thay!");
        }
    }//GEN-LAST:event_bt_tailaiActionPerformed

    private void bt_dangxuat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dangxuat5ActionPerformed
       int xacnhan= JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất chương trình ?","Đăng xuất",JOptionPane.YES_NO_OPTION);
        if(xacnhan==JOptionPane.YES_OPTION)
        {
            this.dispose();
            new DangNhap().setVisible(true);
        }
    }//GEN-LAST:event_bt_dangxuat5ActionPerformed

    private void bt_sanpham5bt_sanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sanpham5bt_sanphamActionPerformed
        new SanPham().setVisible(true);
        
    }//GEN-LAST:event_bt_sanpham5bt_sanphamActionPerformed

    private void bt_lichchieu5bt_lichchieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_lichchieu5bt_lichchieuActionPerformed
        new QLLichChieuPhim().setVisible(true);
    }//GEN-LAST:event_bt_lichchieu5bt_lichchieuActionPerformed

    private void bt_loaiphim5bt_loaiphimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loaiphim5bt_loaiphimActionPerformed
        new LoaiPhim().setVisible(true);
    }//GEN-LAST:event_bt_loaiphim5bt_loaiphimActionPerformed

    private void bt_thanhvien5bt_thanhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_thanhvien5bt_thanhvienActionPerformed
        new QLThanhVien().setVisible(true);
    }//GEN-LAST:event_bt_thanhvien5bt_thanhvienActionPerformed

    private void panel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_exitMouseClicked
       System.exit(0);//tắt tab
       
    }//GEN-LAST:event_panel_exitMouseClicked

    private void panel_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_exitMouseEntered
        panel_exit.setBackground(new Color(162, 222, 208));
    }//GEN-LAST:event_panel_exitMouseEntered

    private void panel_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_exitMouseExited
        panel_exit.setBackground(new Color(244,249,248));
    }//GEN-LAST:event_panel_exitMouseExited

    private void panel_dongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dongMouseClicked
        this.setState(QLThanhVien.ICONIFIED);//đóng
    }//GEN-LAST:event_panel_dongMouseClicked

    private void panel_dongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dongMouseEntered
        panel_dong.setBackground(new Color(162, 222, 208));
    }//GEN-LAST:event_panel_dongMouseEntered

    private void panel_dongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dongMouseExited
        panel_dong.setBackground(new Color(244,249,248));
    }//GEN-LAST:event_panel_dongMouseExited

    private void bt_phim5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_phim5ActionPerformed
        new QuanLyPhim().setVisible(true);
    }//GEN-LAST:event_bt_phim5ActionPerformed

    private void bt_datve5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_datve5ActionPerformed
        new DatVe().setVisible(true);
    }//GEN-LAST:event_bt_datve5ActionPerformed

    private void bt_hoadon5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hoadon5ActionPerformed
        tabquanly.setSelectedIndex(2);
    }//GEN-LAST:event_bt_hoadon5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        showHoaDon();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void bt_baocao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_baocao5ActionPerformed
        new BaoCao().setVisible(true);
    }//GEN-LAST:event_bt_baocao5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable KM_table;
    private javax.swing.JTable Table_hoadon2;
    private javax.swing.JPanel baocaothem;
    private javax.swing.JButton bt_baocao5;
    private javax.swing.JButton bt_dangxuat5;
    private javax.swing.JButton bt_datve5;
    private javax.swing.JButton bt_hoadon5;
    private javax.swing.JButton bt_khuyenmai5;
    private javax.swing.JButton bt_lichchieu5;
    private javax.swing.JButton bt_loaiphim5;
    private javax.swing.JButton bt_nhanvien5;
    private javax.swing.JButton bt_phim5;
    private javax.swing.JButton bt_sanpham5;
    private javax.swing.JButton bt_sualp;
    private javax.swing.JButton bt_taikhoan5;
    private javax.swing.JButton bt_tailai;
    private javax.swing.JButton bt_thanhvien5;
    private javax.swing.JButton bt_themlp;
    private javax.swing.JButton bt_trangchu;
    private javax.swing.JButton bt_xoalp;
    private javax.swing.JPanel hide;
    private javax.swing.JPanel hoadonthem;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel khuyenmaithem;
    private javax.swing.JLabel lb_gioitinh;
    private javax.swing.JLabel lb_hoten;
    private javax.swing.JLabel lb_matk;
    private javax.swing.JLabel lb_ngaysinh;
    private javax.swing.JLabel lb_sdt;
    private javax.swing.JLabel lb_tentk;
    private javax.swing.JPanel panel_dong;
    private javax.swing.JPanel panel_exit;
    private javax.swing.JPanel panel_hoadon;
    private javax.swing.JPanel slidemenu;
    private javax.swing.JTabbedPane tabquanly;
    private javax.swing.JPanel taikhoanthem;
    private javax.swing.JTextField tf_timkiem;
    private javax.swing.JPanel trangchuthem;
    // End of variables declaration//GEN-END:variables
}
