/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import controller.LPhim_ctrl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.LPhim;
import java.awt.*;

/**
 *
 * @author ASUS
 */
public class LoaiPhim extends javax.swing.JFrame {
    //LPhim_service lphim_service; // tạo 1 biến class Lphim_service
    LPhim_ctrl lPhim_ctrl;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form LoaiPhim
     */
    public LoaiPhim() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);//chạy chương trình
        //lphim_service = new LPhim_service();
        lPhim_ctrl = new LPhim_ctrl();
        //tạo 1 đối tương table
        defaultTableModel  = new DefaultTableModel(){
            @Override //ko cho phép chỉnh sửa trên bảng
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        //add các cột vào
        defaultTableModel.addColumn("MaLP");
        defaultTableModel.addColumn("TenLP");
        defaultTableModel.addColumn("HinhThuc");
        
        LP_table.setModel(defaultTableModel);
        
        
        ListAllLP(lPhim_ctrl.getAllLPhim());
       
    }
    
    private void ListAllLP(List<LPhim> LPhims){
        for(LPhim lphim : LPhims){
            defaultTableModel.addRow(new Object[]{lphim.getMaLP(), lphim.getTenLP(), lphim.getHinhThuc()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        panel_exit = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panel_dong = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tf_timkiem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LP_table = new javax.swing.JTable();
        bt_sualp = new javax.swing.JButton();
        bt_xoalp = new javax.swing.JButton();
        bt_themlp = new javax.swing.JButton();
        bt_tailai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(780, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("QUẢN LÝ LOẠI PHIM");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 0, 563, 100));

        panel_exit.setBackground(new java.awt.Color(51, 51, 51));
        panel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_exitMouseExited(evt);
            }
        });
        panel_exit.setLayout(null);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("X");
        panel_exit.add(jLabel7);
        jLabel7.setBounds(0, 10, 30, 20);

        jPanel1.add(panel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 30, 46));

        panel_dong.setBackground(new java.awt.Color(51, 51, 51));
        panel_dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_dongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_dongMouseExited(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("_");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panel_dongLayout = new javax.swing.GroupLayout(panel_dong);
        panel_dong.setLayout(panel_dongLayout);
        panel_dongLayout.setHorizontalGroup(
            panel_dongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panel_dongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_dongLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_dongLayout.setVerticalGroup(
            panel_dongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(panel_dongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dongLayout.createSequentialGroup()
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(panel_dong, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        bg1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 100));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_timkiem.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tf_timkiem.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_timkiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_timkiemActionPerformed(evt);
            }
        });
        jPanel4.add(tf_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 342, 38));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nhập mã loại phim cần tra cứu:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 224, 38));

        LP_table.setAutoCreateRowSorter(true);
        LP_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Loại Phim", "Tên Loại Phim", "Hình Thức"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        LP_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        LP_table.setSelectionBackground(new java.awt.Color(122, 72, 221));
        LP_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        LP_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(LP_table);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 697, 284));

        bt_sualp.setBackground(new java.awt.Color(51, 51, 51));
        bt_sualp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bt_sualp.setForeground(new java.awt.Color(255, 255, 255));
        bt_sualp.setText("Sửa Loại Phim");
        bt_sualp.setAlignmentX(0.5F);
        bt_sualp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_sualp.setMaximumSize(new java.awt.Dimension(130, 30));
        bt_sualp.setMinimumSize(new java.awt.Dimension(130, 30));
        bt_sualp.setPreferredSize(new java.awt.Dimension(130, 30));
        bt_sualp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sualpActionPerformed(evt);
            }
        });
        jPanel4.add(bt_sualp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 129, 52));

        bt_xoalp.setBackground(new java.awt.Color(51, 51, 51));
        bt_xoalp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bt_xoalp.setForeground(new java.awt.Color(255, 255, 255));
        bt_xoalp.setText("Xoá Loại Phim");
        bt_xoalp.setAlignmentX(0.5F);
        bt_xoalp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_xoalp.setPreferredSize(new java.awt.Dimension(130, 30));
        bt_xoalp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoalpActionPerformed(evt);
            }
        });
        jPanel4.add(bt_xoalp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, 50));

        bt_themlp.setBackground(new java.awt.Color(51, 51, 51));
        bt_themlp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bt_themlp.setForeground(new java.awt.Color(255, 255, 255));
        bt_themlp.setText("Thêm Loại Phim");
        bt_themlp.setAlignmentX(0.5F);
        bt_themlp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_themlp.setMaximumSize(new java.awt.Dimension(130, 30));
        bt_themlp.setMinimumSize(new java.awt.Dimension(130, 30));
        bt_themlp.setPreferredSize(new java.awt.Dimension(130, 30));
        bt_themlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themlpActionPerformed(evt);
            }
        });
        jPanel4.add(bt_themlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 140, 50));

        bt_tailai.setBackground(new java.awt.Color(51, 51, 51));
        bt_tailai.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bt_tailai.setForeground(new java.awt.Color(255, 255, 255));
        bt_tailai.setText("Tải Lại");
        bt_tailai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tailaiActionPerformed(evt);
            }
        });
        jPanel4.add(bt_tailai, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 73, 42));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 780, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_timkiemActionPerformed

    private void bt_tailaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tailaiActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        LPhim lPhim;
        //ListAllLP(lphim_service.getAllLPhim());
        
        if(tf_timkiem.getText().equals("")){
            ListAllLP(lPhim_ctrl.getAllLPhim());
        }
        else {
            lPhim = lPhim_ctrl.getLP(tf_timkiem.getText());
            if(lPhim != null){
                defaultTableModel.addRow(new Object[]{lPhim.getMaLP(),lPhim.getTenLP(),lPhim.getHinhThuc()});
            }
            else JOptionPane.showMessageDialog(this,"Khong tim thay!");
        }
    }//GEN-LAST:event_bt_tailaiActionPerformed

    private void bt_themlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themlpActionPerformed
        // TODO add your handling code here:
        new ThemmoiLP().setVisible(true); //chuyển sang frame thêm mới loại phim
        this.dispose(); //ẩn frame loại phim đi
    }//GEN-LAST:event_bt_themlpActionPerformed

    private void bt_xoalpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoalpActionPerformed
        // TODO add your handling code here:
        LPhim_ctrl lphim_ctrl = new LPhim_ctrl();
        int row = LP_table.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(LoaiPhim.this, "Vui long chon loai phim can xoa", "Loi",JOptionPane.ERROR_MESSAGE);
        }
        else{
            int confirm = JOptionPane.showConfirmDialog(LoaiPhim.this, "Ban chac chan muon xoa khong?","Xac Nhan",JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION){
                String malp = String.valueOf(LP_table.getValueAt(row, 0)); //row: hàng đã chọn, 0 là cột đầu tiền trong hàng(mã lp)
                //lphim_service.XoaLP(malp);
                lphim_ctrl.XoaLP(malp);
                defaultTableModel.setRowCount(0);
                ListAllLP(lPhim_ctrl.getAllLPhim());
            }
        }
    }//GEN-LAST:event_bt_xoalpActionPerformed

    private void bt_sualpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sualpActionPerformed
        // TODO add your handling code here:
         int row = LP_table.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(LoaiPhim.this, "Chon loai phim can sua truoc", "Loi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String malp = String.valueOf(LP_table.getValueAt(row, 0));  
            
            new SuaLP(malp).setVisible(true); // chuyen sang frame chinh sua loai phim
            this.dispose(); //an frame cu~ di
        }
        
    }//GEN-LAST:event_bt_sualpActionPerformed

    private void panel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_exitMouseClicked
        this.dispose(); //tắt tab

    }//GEN-LAST:event_panel_exitMouseClicked

    private void panel_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_exitMouseEntered
        panel_exit.setBackground(new Color(162, 222, 208));
    }//GEN-LAST:event_panel_exitMouseEntered

    private void panel_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_exitMouseExited
        panel_exit.setBackground(new Color(244,249,248));
    }//GEN-LAST:event_panel_exitMouseExited

    private void panel_dongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dongMouseClicked
        this.setState(QLThanhVien.ICONIFIED);//đóng
    }//GEN-LAST:event_panel_dongMouseClicked

    private void panel_dongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dongMouseEntered
        panel_dong.setBackground(new Color(162, 222, 208));
    }//GEN-LAST:event_panel_dongMouseEntered

    private void panel_dongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dongMouseExited
        panel_dong.setBackground(new Color(244,249,248));
    }//GEN-LAST:event_panel_dongMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaiPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaiPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaiPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaiPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoaiPhim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LP_table;
    private javax.swing.JPanel bg1;
    private javax.swing.JButton bt_sualp;
    private javax.swing.JButton bt_tailai;
    private javax.swing.JButton bt_themlp;
    private javax.swing.JButton bt_xoalp;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_dong;
    private javax.swing.JPanel panel_exit;
    private javax.swing.JTextField tf_timkiem;
    // End of variables declaration//GEN-END:variables
}
