/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ASUS
 */
public class QuanLyPhim extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyPhim
     */
    public QuanLyPhim() {
        initComponents();
        String anh1 = "D:\\UIT\\java\\project\\DoAnCinemas\\src\\Anh_Phim\\Doraemon.jpg";
        String anh2 = "D:\\UIT\\java\\project\\DoAnCinemas\\src\\Anh_Phim\\Cruella.jpg";
        String anh3 = "D:\\UIT\\java\\project\\DoAnCinemas\\src\\Anh_Phim\\DemTroiBuoc.jpg";
        String anh4 = "D:\\UIT\\java\\project\\DoAnCinemas\\src\\Anh_Phim\\DuaBe.jpg";
        String anh5 = "D:\\UIT\\java\\project\\DoAnCinemas\\src\\Anh_Phim\\Spirit.jpg";
        String anh6 = "D:\\UIT\\java\\project\\DoAnCinemas\\src\\Anh_Phim\\ff9-fast-furious-9.jpg";
        scaleIMG(anh1,label_anh01);
        scaleIMG(anh2,label_anh2);
        scaleIMG(anh3,label_anh3);
        scaleIMG(anh4,label_anh4);
        scaleIMG(anh5,label_anh5);
        scaleIMG(anh6,label_anh6);
    }
    
    public void scaleIMG(String linkanhString, JLabel lbLabel){
        ImageIcon icon = new ImageIcon(linkanhString);
        
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(lbLabel.getWidth(), lbLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        lbLabel.setIcon(scaleIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_phim = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        Pn_01 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        label_anh01 = new javax.swing.JLabel();
        Pn_2 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        label_anh2 = new javax.swing.JLabel();
        Pn_3 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        label_anh3 = new javax.swing.JLabel();
        Pn_4 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        label_anh4 = new javax.swing.JLabel();
        Pn_5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        label_anh5 = new javax.swing.JLabel();
        Pn_6 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        label_anh6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panel_phim.setBackground(new java.awt.Color(51, 51, 51));
        panel_phim.setLayout(null);

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setForeground(new java.awt.Color(102, 102, 102));

        jLabel24.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("QUẢN LÝ PHIM");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panel_phim.add(jPanel13);
        jPanel13.setBounds(0, 0, 870, 50);

        Pn_01.setBackground(new java.awt.Color(255, 255, 255));
        Pn_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pn_01MouseClicked(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 153, 153));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Stand by me 2");

        javax.swing.GroupLayout Pn_01Layout = new javax.swing.GroupLayout(Pn_01);
        Pn_01.setLayout(Pn_01Layout);
        Pn_01Layout.setHorizontalGroup(
            Pn_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_01Layout.createSequentialGroup()
                .addGroup(Pn_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_01Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_anh01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Pn_01Layout.setVerticalGroup(
            Pn_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_anh01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_phim.add(Pn_01);
        Pn_01.setBounds(30, 70, 200, 250);

        Pn_2.setBackground(new java.awt.Color(255, 255, 255));
        Pn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pn_2MouseClicked(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 153, 153));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("CRUELLA");

        javax.swing.GroupLayout Pn_2Layout = new javax.swing.GroupLayout(Pn_2);
        Pn_2.setLayout(Pn_2Layout);
        Pn_2Layout.setHorizontalGroup(
            Pn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_2Layout.createSequentialGroup()
                .addGroup(Pn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_anh2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Pn_2Layout.setVerticalGroup(
            Pn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_anh2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_phim.add(Pn_2);
        Pn_2.setBounds(330, 70, 200, 250);

        Pn_3.setBackground(new java.awt.Color(255, 255, 255));
        Pn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pn_3MouseClicked(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 153, 153));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Dem Troi Buoc");

        javax.swing.GroupLayout Pn_3Layout = new javax.swing.GroupLayout(Pn_3);
        Pn_3.setLayout(Pn_3Layout);
        Pn_3Layout.setHorizontalGroup(
            Pn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_3Layout.createSequentialGroup()
                .addGroup(Pn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_anh3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Pn_3Layout.setVerticalGroup(
            Pn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_anh3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_phim.add(Pn_3);
        Pn_3.setBounds(620, 70, 200, 250);

        Pn_4.setBackground(new java.awt.Color(255, 255, 255));
        Pn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pn_4MouseClicked(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 153, 153));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Dua be");

        javax.swing.GroupLayout Pn_4Layout = new javax.swing.GroupLayout(Pn_4);
        Pn_4.setLayout(Pn_4Layout);
        Pn_4Layout.setHorizontalGroup(
            Pn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_4Layout.createSequentialGroup()
                .addGroup(Pn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_anh4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Pn_4Layout.setVerticalGroup(
            Pn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_anh4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_phim.add(Pn_4);
        Pn_4.setBounds(30, 340, 200, 250);

        Pn_5.setBackground(new java.awt.Color(255, 255, 255));
        Pn_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pn_5MouseClicked(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 153, 153));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("SPIRIT");

        javax.swing.GroupLayout Pn_5Layout = new javax.swing.GroupLayout(Pn_5);
        Pn_5.setLayout(Pn_5Layout);
        Pn_5Layout.setHorizontalGroup(
            Pn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_5Layout.createSequentialGroup()
                .addGroup(Pn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_anh5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Pn_5Layout.setVerticalGroup(
            Pn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_anh5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_phim.add(Pn_5);
        Pn_5.setBounds(330, 340, 200, 250);

        Pn_6.setBackground(new java.awt.Color(255, 255, 255));
        Pn_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pn_6MouseClicked(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 153, 153));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("FAST & FURIOUS 9");

        javax.swing.GroupLayout Pn_6Layout = new javax.swing.GroupLayout(Pn_6);
        Pn_6.setLayout(Pn_6Layout);
        Pn_6Layout.setHorizontalGroup(
            Pn_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_6Layout.createSequentialGroup()
                .addGroup(Pn_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_anh6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Pn_6Layout.setVerticalGroup(
            Pn_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_anh6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_phim.add(Pn_6);
        Pn_6.setBounds(620, 340, 200, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_phim, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_phim, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Pn_01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pn_01MouseClicked
        // TODO add your handling code here:
    String maphim = "1p";
    ChiTietPhim ct = new ChiTietPhim(maphim);
    }//GEN-LAST:event_Pn_01MouseClicked

    private void Pn_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pn_2MouseClicked
        // TODO add your handling code here:
         String maphim = "2p";
    ChiTietPhim ct = new ChiTietPhim(maphim);
    }//GEN-LAST:event_Pn_2MouseClicked

    private void Pn_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pn_3MouseClicked
        // TODO add your handling code here:
         String maphim = "3p";
    ChiTietPhim ct = new ChiTietPhim(maphim);
    }//GEN-LAST:event_Pn_3MouseClicked

    private void Pn_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pn_4MouseClicked
        // TODO add your handling code here:
         String maphim = "4p";
    ChiTietPhim ct = new ChiTietPhim(maphim);
    }//GEN-LAST:event_Pn_4MouseClicked

    private void Pn_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pn_5MouseClicked
        // TODO add your handling code here:
         String maphim = "5p";
    ChiTietPhim ct = new ChiTietPhim(maphim);
    }//GEN-LAST:event_Pn_5MouseClicked

    private void Pn_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pn_6MouseClicked
        // TODO add your handling code here:
         String maphim = "6p";
    ChiTietPhim ct = new ChiTietPhim(maphim);
    }//GEN-LAST:event_Pn_6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pn_01;
    private javax.swing.JPanel Pn_2;
    private javax.swing.JPanel Pn_3;
    private javax.swing.JPanel Pn_4;
    private javax.swing.JPanel Pn_5;
    private javax.swing.JPanel Pn_6;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JLabel label_anh01;
    private javax.swing.JLabel label_anh2;
    private javax.swing.JLabel label_anh3;
    private javax.swing.JLabel label_anh4;
    private javax.swing.JLabel label_anh5;
    private javax.swing.JLabel label_anh6;
    private javax.swing.JPanel panel_phim;
    // End of variables declaration//GEN-END:variables
}
