/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

//import Controller.Oracle;
import controller.TaiKhoan_ctrl;
import java.awt.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Phon
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        iconhide.setVisible(false);
        this.setLocationRelativeTo(null);//hiển thị giữa màn hình
        this.setTitle("Đăng nhập");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);//thoát chương trình khi bấm exit
        //this.setVisible(true);//chạy chương trình
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_pass = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        button_login = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        label_unive1 = new javax.swing.JLabel();
        iconshow = new javax.swing.JLabel();
        iconhide = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_pass.setForeground(new java.awt.Color(51, 51, 51));
        label_pass.setText("Mật Khẩu");
        jPanel1.add(label_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 40));

        label_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_username.setForeground(new java.awt.Color(51, 51, 51));
        label_username.setText("Tên đăng nhập");
        jPanel1.add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 40));

        txt_username.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_username.setForeground(new java.awt.Color(153, 153, 153));
        txt_username.setText("Tên đăng nhập");
        txt_username.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 230, 30));

        txt_pass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(153, 153, 153));
        txt_pass.setText("password");
        txt_pass.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passFocusLost(evt);
            }
        });
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 230, 30));

        button_login.setBackground(new java.awt.Color(255, 255, 255));
        button_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_login.setText("Đăng nhập");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });
        jPanel1.add(button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 120, 40));

        button_cancel.setBackground(new java.awt.Color(255, 255, 255));
        button_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_cancel.setText("Hủy");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(button_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 110, 40));

        label_unive1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        label_unive1.setForeground(new java.awt.Color(51, 51, 51));
        label_unive1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_unive1.setText("Đăng Nhập");
        jPanel1.add(label_unive1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 260, 60));

        iconshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/eye-with-thick-outline-variant (1).png"))); // NOI18N
        iconshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconshowMousePressed(evt);
            }
        });
        jPanel1.add(iconshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        iconhide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/invisible.png"))); // NOI18N
        iconhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconhideMousePressed(evt);
            }
        });
        jPanel1.add(iconhide, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 0, 470, 400));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconImage/ezgif.com-crop.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 552, Short.MAX_VALUE)
                .addGap(476, 476, 476))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed

        String username = txt_username.getText();
        String password = String.valueOf(txt_pass.getPassword());
        TaiKhoan_ctrl tkc = new TaiKhoan_ctrl();
        try {
            
            if(tkc.Login(username, password))
            {
                if(TaiKhoan_ctrl.LoaiTaiKhoan(username).equals("quanly")){
                MaNV=tkc.getThongTinDangNhap(username);
                //hiển thị frame trang chủ
                new Home().setVisible(true);
                //Đóng đăng nhập
                this.dispose();}
                else{
                MaNV=tkc.getThongTinDangNhap(username);
                //hiển thị frame trang chủ
                new Home1().setVisible(true);
                //Đóng đăng nhập
                this.dispose();
                    
                    
                }
            }
            else
            {
             // hiển thị lỗi
                JOptionPane.showMessageDialog(null,"Sai Tên đăng nhập/ Mật khẩu","Login error",2);
               
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
              
    }//GEN-LAST:event_button_loginActionPerformed

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        //clear username khi click chuột
        if(txt_username.getText().trim().equals("Tên đăng nhập"))
        {
            txt_username.setText("");
            txt_username.setForeground(Color.BLACK);
        }
          
        
    }//GEN-LAST:event_txt_usernameFocusGained

    private void txt_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passFocusLost
         String pass = String.valueOf(txt_pass.getPassword());
          if(pass.trim().equals("")||
           pass.trim().toLowerCase().equals("password"))
        {
            txt_pass.setText("password");
            txt_pass.setForeground(new Color (153,153,153));
        }
    }//GEN-LAST:event_txt_passFocusLost

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_button_cancelActionPerformed

    private void txt_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passFocusGained
        //clear password khi click chuột vào password
        String pass = String.valueOf(txt_pass.getPassword());
        
        if(pass.trim().toLowerCase().equals("password"))
        {
            txt_pass.setText("");
            txt_pass.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_txt_passFocusGained

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
       //hiển thị "username" khi click trường khác
        if(txt_username.getText().trim().equals("")||
           txt_username.getText().trim().toLowerCase().equals("Tên đăng nhập"))
        {
            txt_username.setText("Tên đăng nhập");
            txt_username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void iconshowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconshowMousePressed
        iconshow.setVisible(false);
        iconhide.setVisible(true);
        txt_pass.setEchoChar((char)0);
    }//GEN-LAST:event_iconshowMousePressed

    private void iconhideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconhideMousePressed
       iconhide.setVisible(false);
       iconshow.setVisible(true);
       txt_pass.setEchoChar('*');
    }//GEN-LAST:event_iconhideMousePressed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
            
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_login;
    private javax.swing.JLabel iconhide;
    private javax.swing.JLabel iconshow;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_pass;
    private javax.swing.JLabel label_unive1;
    private javax.swing.JLabel label_username;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
    public static String MaNV;
    

   
    
}
