/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import controller.DatVe_ctrl;
import controller.JDBCConnection;
import controller.SuatChieu_ctrl_test;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.*;
import javax.swing.JComboBox;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JToggleButton;
/**
 *
 * @author Phi Long
 */
public class DatVe extends javax.swing.JFrame {

    /**
     * Creates new form DatVe
     */
    public DatVe() {
        initComponents();
        this.setLocationRelativeTo(null);//hiển thị giữa màn hình
        this.setVisible(true);//chạy chương trình
        HienThiNgayChieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        line1 = new javax.swing.JPanel();
        Label_ngaychieu = new javax.swing.JLabel();
        cbb_ngaychieu = new javax.swing.JComboBox<>();
        cbb_loaiphim = new javax.swing.JComboBox<>();
        Label_loaiphim = new javax.swing.JLabel();
        cbb_phim = new javax.swing.JComboBox<>();
        Label_phim = new javax.swing.JLabel();
        cbb_giochieu = new javax.swing.JComboBox<>();
        Label_ngaychieu3 = new javax.swing.JLabel();
        panel_ve = new javax.swing.JPanel();
        Label_ngaychieu1 = new javax.swing.JLabel();
        Label_loaiphim1 = new javax.swing.JLabel();
        label_loaiphimve = new javax.swing.JLabel();
        label_ngaychieu_ve = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_tenphim_ve = new javax.swing.JLabel();
        Label_rapphim = new javax.swing.JLabel();
        Label_ghe = new javax.swing.JLabel();
        label_rapchieu_ve = new javax.swing.JLabel();
        label_ghe_ve = new javax.swing.JLabel();
        Label_giochieu1 = new javax.swing.JLabel();
        label_suatchieu_ve = new javax.swing.JLabel();
        Label_gia = new javax.swing.JLabel();
        label_gia_ve = new javax.swing.JLabel();
        line2 = new javax.swing.JPanel();
        panel_ghexemphim = new javax.swing.JPanel();
        Panel_manhinh = new javax.swing.JPanel();
        label_manhinh = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        A1 = new javax.swing.JToggleButton();
        A2 = new javax.swing.JToggleButton();
        A3 = new javax.swing.JToggleButton();
        A4 = new javax.swing.JToggleButton();
        A5 = new javax.swing.JToggleButton();
        A6 = new javax.swing.JToggleButton();
        B1 = new javax.swing.JToggleButton();
        B2 = new javax.swing.JToggleButton();
        B3 = new javax.swing.JToggleButton();
        B4 = new javax.swing.JToggleButton();
        B5 = new javax.swing.JToggleButton();
        B6 = new javax.swing.JToggleButton();
        C1 = new javax.swing.JToggleButton();
        C2 = new javax.swing.JToggleButton();
        C3 = new javax.swing.JToggleButton();
        C4 = new javax.swing.JToggleButton();
        C5 = new javax.swing.JToggleButton();
        C6 = new javax.swing.JToggleButton();
        D1 = new javax.swing.JToggleButton();
        D2 = new javax.swing.JToggleButton();
        D3 = new javax.swing.JToggleButton();
        D4 = new javax.swing.JToggleButton();
        D5 = new javax.swing.JToggleButton();
        D6 = new javax.swing.JToggleButton();
        E1 = new javax.swing.JToggleButton();
        E2 = new javax.swing.JToggleButton();
        E3 = new javax.swing.JToggleButton();
        E4 = new javax.swing.JToggleButton();
        E5 = new javax.swing.JToggleButton();
        E6 = new javax.swing.JToggleButton();
        jLabel55 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        button_xacnhan = new javax.swing.JButton();
        bt_thanhtoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        bar.setBackground(new java.awt.Color(153, 153, 153));
        bar.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        line1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout line1Layout = new javax.swing.GroupLayout(line1);
        line1.setLayout(line1Layout);
        line1Layout.setHorizontalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        line1Layout.setVerticalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 640, 10));

        Label_ngaychieu.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Label_ngaychieu.setForeground(new java.awt.Color(255, 255, 255));
        Label_ngaychieu.setText("Ngày chiếu: ");
        jPanel2.add(Label_ngaychieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        cbb_ngaychieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_ngaychieuActionPerformed(evt);
            }
        });
        jPanel2.add(cbb_ngaychieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 240, -1));

        cbb_loaiphim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_loaiphimActionPerformed(evt);
            }
        });
        jPanel2.add(cbb_loaiphim, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 240, -1));

        Label_loaiphim.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Label_loaiphim.setForeground(new java.awt.Color(255, 255, 255));
        Label_loaiphim.setText("Loại phim:");
        jPanel2.add(Label_loaiphim, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        cbb_phim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_phimActionPerformed(evt);
            }
        });
        jPanel2.add(cbb_phim, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 240, -1));

        Label_phim.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Label_phim.setForeground(new java.awt.Color(255, 255, 255));
        Label_phim.setText("Phim:");
        jPanel2.add(Label_phim, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        cbb_giochieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "24-06-2021", "25-07-2021", "26-07-2021", "27-07-2021" }));
        cbb_giochieu.setSelectedIndex(-1);
        cbb_giochieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_giochieuActionPerformed(evt);
            }
        });
        jPanel2.add(cbb_giochieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 240, -1));

        Label_ngaychieu3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Label_ngaychieu3.setForeground(new java.awt.Color(255, 255, 255));
        Label_ngaychieu3.setText("Giờ chiếu:");
        jPanel2.add(Label_ngaychieu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        Label_ngaychieu1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Label_ngaychieu1.setText("Ngày chiếu: ");

        Label_loaiphim1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Label_loaiphim1.setText("Loại Phim:");

        label_loaiphimve.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        label_loaiphimve.setText("Loại phim ");

        label_ngaychieu_ve.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        label_ngaychieu_ve.setText("Ngày chiếu phim");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Emperor Cinemas");

        label_tenphim_ve.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label_tenphim_ve.setText("Tên Phim");

        Label_rapphim.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Label_rapphim.setText("Rạp:");

        Label_ghe.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Label_ghe.setText("Ghế:");

        label_rapchieu_ve.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        label_rapchieu_ve.setText("rạp");

        label_ghe_ve.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N

        Label_giochieu1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Label_giochieu1.setText("Suất chiếu:");

        label_suatchieu_ve.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        label_suatchieu_ve.setText("Giờ chiếu");

        Label_gia.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        Label_gia.setText("Giá:");

        label_gia_ve.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        label_gia_ve.setText("0");

        javax.swing.GroupLayout panel_veLayout = new javax.swing.GroupLayout(panel_ve);
        panel_ve.setLayout(panel_veLayout);
        panel_veLayout.setHorizontalGroup(
            panel_veLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_veLayout.createSequentialGroup()
                .addGroup(panel_veLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_veLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(panel_veLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_veLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel_veLayout.createSequentialGroup()
                                .addComponent(Label_giochieu1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_suatchieu_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_veLayout.createSequentialGroup()
                                .addGroup(panel_veLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_loaiphim1)
                                    .addComponent(Label_ngaychieu1))
                                .addGap(46, 46, 46)
                                .addGroup(panel_veLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_ngaychieu_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_loaiphimve, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel_veLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_veLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_veLayout.createSequentialGroup()
                                .addComponent(Label_gia)
                                .addGap(19, 19, 19)
                                .addComponent(label_gia_ve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_veLayout.createSequentialGroup()
                                .addComponent(Label_rapphim)
                                .addGap(19, 19, 19)
                                .addComponent(label_rapchieu_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(Label_ghe)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_ghe_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_veLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_tenphim_ve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_veLayout.setVerticalGroup(
            panel_veLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_veLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(panel_veLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ngaychieu1)
                    .addComponent(label_ngaychieu_ve))
                .addGap(18, 18, 18)
                .addGroup(panel_veLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_loaiphim1)
                    .addComponent(label_loaiphimve))
                .addGap(18, 18, 18)
                .addGroup(panel_veLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_giochieu1)
                    .addComponent(label_suatchieu_ve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_tenphim_ve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_veLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_rapchieu_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_rapphim)
                    .addComponent(Label_ghe)
                    .addComponent(label_ghe_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_veLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_gia_ve, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_gia))
                .addGap(40, 40, 40))
        );

        jPanel2.add(panel_ve, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 340, 320));

        line2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout line2Layout = new javax.swing.GroupLayout(line2);
        line2.setLayout(line2Layout);
        line2Layout.setHorizontalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        line2Layout.setVerticalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jPanel2.add(line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 630));

        panel_ghexemphim.setBackground(new java.awt.Color(51, 51, 51));
        panel_ghexemphim.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_manhinh.setBackground(new java.awt.Color(153, 153, 153));

        label_manhinh.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label_manhinh.setForeground(new java.awt.Color(255, 255, 255));
        label_manhinh.setText("MÀN HÌNH");

        javax.swing.GroupLayout Panel_manhinhLayout = new javax.swing.GroupLayout(Panel_manhinh);
        Panel_manhinh.setLayout(Panel_manhinhLayout);
        Panel_manhinhLayout.setHorizontalGroup(
            Panel_manhinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_manhinhLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(label_manhinh, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        Panel_manhinhLayout.setVerticalGroup(
            Panel_manhinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_manhinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_ghexemphim.add(Panel_manhinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new java.awt.GridLayout(5, 6, 10, 22));

        A1.setText("A1");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        jPanel3.add(A1);

        A2.setText("A2");
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        jPanel3.add(A2);

        A3.setText("A3");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        jPanel3.add(A3);

        A4.setText("A4");
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        jPanel3.add(A4);

        A5.setText("A5");
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        jPanel3.add(A5);

        A6.setText("A6");
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });
        jPanel3.add(A6);

        B1.setText("B1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel3.add(B1);

        B2.setText("B2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel3.add(B2);

        B3.setText("B3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel3.add(B3);

        B4.setText("B4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jPanel3.add(B4);

        B5.setText("B5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        jPanel3.add(B5);

        B6.setText("B6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        jPanel3.add(B6);

        C1.setText("C1");
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        jPanel3.add(C1);

        C2.setText("C2");
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        jPanel3.add(C2);

        C3.setText("C3");
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        jPanel3.add(C3);

        C4.setText("C4");
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });
        jPanel3.add(C4);

        C5.setText("C5");
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });
        jPanel3.add(C5);

        C6.setText("C6");
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });
        jPanel3.add(C6);

        D1.setText("D1");
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });
        jPanel3.add(D1);

        D2.setText("D2");
        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });
        jPanel3.add(D2);

        D3.setText("D3");
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });
        jPanel3.add(D3);

        D4.setText("D4");
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4ActionPerformed(evt);
            }
        });
        jPanel3.add(D4);

        D5.setText("D5");
        D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D5ActionPerformed(evt);
            }
        });
        jPanel3.add(D5);

        D6.setText("D6");
        D6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D6ActionPerformed(evt);
            }
        });
        jPanel3.add(D6);

        E1.setText("E1");
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });
        jPanel3.add(E1);

        E2.setText("E2");
        E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2ActionPerformed(evt);
            }
        });
        jPanel3.add(E2);

        E3.setText("E3");
        E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3ActionPerformed(evt);
            }
        });
        jPanel3.add(E3);

        E4.setText("E4");
        E4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E4ActionPerformed(evt);
            }
        });
        jPanel3.add(E4);

        E5.setText("E5");
        E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5ActionPerformed(evt);
            }
        });
        jPanel3.add(E5);

        E6.setText("E6");
        E6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E6ActionPerformed(evt);
            }
        });
        jPanel3.add(E6);

        panel_ghexemphim.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 540, 300));

        jPanel2.add(panel_ghexemphim, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -10, 630, 510));

        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Ghế đã đặt");
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, -1, -1));

        jPanel56.setBackground(new java.awt.Color(102, 102, 102));
        jPanel56.setLayout(null);
        jPanel2.add(jPanel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, 30, 30));

        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Ghế đã chọn");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 540, -1, -1));

        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Ghế trống");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, -1, -1));

        jPanel57.setBackground(new java.awt.Color(255, 255, 0));
        jPanel57.setLayout(null);
        jPanel2.add(jPanel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 30, 30));

        jPanel58.setBackground(new java.awt.Color(255, 255, 255));
        jPanel58.setLayout(null);
        jPanel2.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, 30, 30));

        button_xacnhan.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        button_xacnhan.setText("Xác Nhận");
        button_xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_xacnhanActionPerformed(evt);
            }
        });
        jPanel2.add(button_xacnhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        bt_thanhtoan.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bt_thanhtoan.setText("Thanh Toán");
        bt_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_thanhtoanActionPerformed(evt);
            }
        });
        jPanel2.add(bt_thanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 110, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
        GheDaChon(A1);
    }//GEN-LAST:event_A1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        GheDaChon(B2);
    }//GEN-LAST:event_B2ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
        GheDaChon(C1);
    }//GEN-LAST:event_C1ActionPerformed

    private void button_xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_xacnhanActionPerformed
        // TODO add your handling code here:
        DoiMauGheDaDat(A1);
        DoiMauGheDaDat(A2);
        DoiMauGheDaDat(A3);
        DoiMauGheDaDat(A4);
        DoiMauGheDaDat(A5);
        DoiMauGheDaDat(A6);
        DoiMauGheDaDat(B1);
        DoiMauGheDaDat(B2);
        DoiMauGheDaDat(B3);
        DoiMauGheDaDat(B4);
        DoiMauGheDaDat(B5);
        DoiMauGheDaDat(B6);
        DoiMauGheDaDat(C1);
        DoiMauGheDaDat(C1);
        DoiMauGheDaDat(C2);
        DoiMauGheDaDat(C4);
        DoiMauGheDaDat(C5);
        DoiMauGheDaDat(C6);
        DoiMauGheDaDat(D1);
        DoiMauGheDaDat(D2);
        DoiMauGheDaDat(D3);
        DoiMauGheDaDat(D4);
        DoiMauGheDaDat(D5);
        DoiMauGheDaDat(D6);
        DoiMauGheDaDat(E1);
        DoiMauGheDaDat(E2);
        DoiMauGheDaDat(E3);
        DoiMauGheDaDat(E4);
        DoiMauGheDaDat(E5);
        DoiMauGheDaDat(E6); 
    }//GEN-LAST:event_button_xacnhanActionPerformed

    private void cbb_ngaychieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_ngaychieuActionPerformed
        // TODO add your handling code here:
        HienThiLoaiPhim();
    }//GEN-LAST:event_cbb_ngaychieuActionPerformed

    private void cbb_loaiphimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_loaiphimActionPerformed
        // TODO add your handling code here:
        HienThiTenPhim();
        label_ngaychieu_ve.setText(cbb_ngaychieu.getSelectedItem().toString());
        
        
        
    }//GEN-LAST:event_cbb_loaiphimActionPerformed

    private void cbb_phimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_phimActionPerformed
        // TODO add your handling code here:
        HienThiThoiGianChieu();
        label_loaiphimve.setText(cbb_loaiphim.getSelectedItem().toString());
        label_tenphim_ve.setText(cbb_phim.getSelectedItem().toString());
        
    }//GEN-LAST:event_cbb_phimActionPerformed

    private void cbb_giochieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_giochieuActionPerformed
        // TODO add your handling code here:
        HienThiRapPhim(cbb_ngaychieu.getSelectedItem().toString(), cbb_phim.getSelectedItem().toString(), cbb_giochieu.getSelectedItem().toString(),label_rapchieu_ve);
        label_suatchieu_ve.setText(cbb_giochieu.getSelectedItem().toString());
    }//GEN-LAST:event_cbb_giochieuActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
        GheDaChon(A2);
    }//GEN-LAST:event_A2ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
        GheDaChon(A3);
    }//GEN-LAST:event_A3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
        GheDaChon(A4);
    }//GEN-LAST:event_A4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        // TODO add your handling code here:
        GheDaChon(A5);
    }//GEN-LAST:event_A5ActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        // TODO add your handling code here:
        GheDaChon(A6);
    }//GEN-LAST:event_A6ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        GheDaChon(B1);
    }//GEN-LAST:event_B1ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        GheDaChon(B3);
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        GheDaChon(B4);
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        GheDaChon(B5);
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
        GheDaChon(B6);
    }//GEN-LAST:event_B6ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        // TODO add your handling code here:
        GheDaChon(C2);
    }//GEN-LAST:event_C2ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        // TODO add your handling code here:
        GheDaChon(C3);
    }//GEN-LAST:event_C3ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        // TODO add your handling code here:
        GheDaChon(C4);
    }//GEN-LAST:event_C4ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        // TODO add your handling code here:
        GheDaChon(C5);
    }//GEN-LAST:event_C5ActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        // TODO add your handling code here:
        GheDaChon(C6);
    }//GEN-LAST:event_C6ActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
        // TODO add your handling code here:
        GheDaChon(D1);
    }//GEN-LAST:event_D1ActionPerformed

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ActionPerformed
        // TODO add your handling code here:
        GheDaChon(D2);
    }//GEN-LAST:event_D2ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        // TODO add your handling code here:
        GheDaChon(D3);
    }//GEN-LAST:event_D3ActionPerformed

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
        // TODO add your handling code here:
        GheDaChon(D4);
    }//GEN-LAST:event_D4ActionPerformed

    private void D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5ActionPerformed
        // TODO add your handling code here:
        GheDaChon(D5);
    }//GEN-LAST:event_D5ActionPerformed

    private void D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6ActionPerformed
        // TODO add your handling code here:
        GheDaChon(D6);
    }//GEN-LAST:event_D6ActionPerformed

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
        // TODO add your handling code here:
        GheDaChon(E1);
    }//GEN-LAST:event_E1ActionPerformed

    private void E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ActionPerformed
        // TODO add your handling code here:
        GheDaChon(E2);
    }//GEN-LAST:event_E2ActionPerformed

    private void E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3ActionPerformed
        // TODO add your handling code here:
        GheDaChon(E3);
    }//GEN-LAST:event_E3ActionPerformed

    private void E4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E4ActionPerformed
        // TODO add your handling code here:
        GheDaChon(E4);
    }//GEN-LAST:event_E4ActionPerformed

    private void E5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5ActionPerformed
        // TODO add your handling code here:
        GheDaChon(E5);
    }//GEN-LAST:event_E5ActionPerformed

    private void E6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E6ActionPerformed
        // TODO add your handling code here:
        GheDaChon(E6);
    }//GEN-LAST:event_E6ActionPerformed

    private void bt_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_thanhtoanActionPerformed
        // TODO add your handling code here:
        tongtien = label_gia_ve.getText();
        tenghe = label_ghe_ve.getText();
        new Thanh_Toan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_thanhtoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatVe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton A1;
    private javax.swing.JToggleButton A2;
    private javax.swing.JToggleButton A3;
    private javax.swing.JToggleButton A4;
    private javax.swing.JToggleButton A5;
    private javax.swing.JToggleButton A6;
    private javax.swing.JToggleButton B1;
    private javax.swing.JToggleButton B2;
    private javax.swing.JToggleButton B3;
    private javax.swing.JToggleButton B4;
    private javax.swing.JToggleButton B5;
    private javax.swing.JToggleButton B6;
    private javax.swing.JToggleButton C1;
    private javax.swing.JToggleButton C2;
    private javax.swing.JToggleButton C3;
    private javax.swing.JToggleButton C4;
    private javax.swing.JToggleButton C5;
    private javax.swing.JToggleButton C6;
    private javax.swing.JToggleButton D1;
    private javax.swing.JToggleButton D2;
    private javax.swing.JToggleButton D3;
    private javax.swing.JToggleButton D4;
    private javax.swing.JToggleButton D5;
    private javax.swing.JToggleButton D6;
    private javax.swing.JToggleButton E1;
    private javax.swing.JToggleButton E2;
    private javax.swing.JToggleButton E3;
    private javax.swing.JToggleButton E4;
    private javax.swing.JToggleButton E5;
    private javax.swing.JToggleButton E6;
    private javax.swing.JLabel Label_ghe;
    private javax.swing.JLabel Label_gia;
    private javax.swing.JLabel Label_giochieu1;
    private javax.swing.JLabel Label_loaiphim;
    private javax.swing.JLabel Label_loaiphim1;
    private javax.swing.JLabel Label_ngaychieu;
    private javax.swing.JLabel Label_ngaychieu1;
    private javax.swing.JLabel Label_ngaychieu3;
    private javax.swing.JLabel Label_phim;
    private javax.swing.JLabel Label_rapphim;
    private javax.swing.JPanel Panel_manhinh;
    private javax.swing.JPanel bar;
    private javax.swing.JButton bt_thanhtoan;
    private javax.swing.JButton button_xacnhan;
    private javax.swing.JComboBox<String> cbb_giochieu;
    private javax.swing.JComboBox<String> cbb_loaiphim;
    private javax.swing.JComboBox<String> cbb_ngaychieu;
    private javax.swing.JComboBox<String> cbb_phim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JLabel label_ghe_ve;
    private javax.swing.JLabel label_gia_ve;
    private javax.swing.JLabel label_loaiphimve;
    private javax.swing.JLabel label_manhinh;
    private javax.swing.JLabel label_ngaychieu_ve;
    private javax.swing.JLabel label_rapchieu_ve;
    private javax.swing.JLabel label_suatchieu_ve;
    private javax.swing.JLabel label_tenphim_ve;
    private javax.swing.JPanel line1;
    private javax.swing.JPanel line2;
    private javax.swing.JPanel panel_ghexemphim;
    private javax.swing.JPanel panel_ve;
    // End of variables declaration//GEN-END:variables
public static String tongtien;
public static String MaSuatChieu;
public SuatChieu_ctrl_test suatChieu_ctrl = new SuatChieu_ctrl_test();
public static String MaRap;
public static Vector<String> MaGhe = new Vector<String>();

    private void DoiMauGheDaDat(javax.swing.JToggleButton a){
    String vitri = a.getText(); // ví dụ A1
    vitri = vitri.toLowerCase(); // -> a1
    String c = vitri.substring(1); // lấy cột -> c = '1';
    String r = vitri.substring(0,1); //lấy hàng -> r = 'a' 
    vitri = "h" + r + " c" + c; // vị trí lúc này -> "ha c1", hàng A cột 1
    
    String NgayChieu = cbb_ngaychieu.getSelectedItem().toString();
    String GioChieu = cbb_giochieu.getSelectedItem().toString();
    String TenPhim = cbb_phim.getSelectedItem().toString();
    
    DatVe_ctrl datVe_ctrl = new DatVe_ctrl();
    SuatChieu_ctrl_test suatChieu_ctrl = new SuatChieu_ctrl_test();
    
    MaSuatChieu  = suatChieu_ctrl.SuatChieuDaChon(NgayChieu, GioChieu, TenPhim);
    ArrayList<String> listGheDaDat = datVe_ctrl.ListGheDaDat(MaSuatChieu);
    
    for(int i = 0; i < listGheDaDat.size(); i++){
        System.out.println(listGheDaDat.get(i));
        if(vitri.equalsIgnoreCase(listGheDaDat.get(i))) //so sanh 2 chuỗi ko phân biệt chữ hoa thường
            a.setBackground(new Color(255,255,0)); // ghế nào có trong list đã đặt thì đổi button thành màu vàng
    }
}

    private void HienThiNgayChieu() {
        Vector<String> listNgayChieu = suatChieu_ctrl.ListNgayChieu();
        //cbb_ngaychieu.setModel(new DefaultComboBoxModel<String>(listNgayChieu.toArray(new String[listNgayChieu.size()])));
        cbb_ngaychieu.setModel(new DefaultComboBoxModel<>(listNgayChieu)); //chưa test
    }

    private void HienThiLoaiPhim() {
        String NgayChieu = cbb_ngaychieu.getSelectedItem().toString();
        Vector<String> listLoaiPhim = new Vector<>();
        listLoaiPhim = suatChieu_ctrl.ListLoaiPhim(NgayChieu);
        cbb_loaiphim.setModel(new DefaultComboBoxModel<>(listLoaiPhim));
        
    }

    private void HienThiTenPhim() {
        String NgayChieu = cbb_ngaychieu.getSelectedItem().toString();
        String LoaiPhim = cbb_loaiphim.getSelectedItem().toString();
        Vector<String> TenPhim = suatChieu_ctrl.ListPhim(NgayChieu, LoaiPhim);
        cbb_phim.setModel(new DefaultComboBoxModel<>(TenPhim));
        
    }

    private void HienThiThoiGianChieu() {
        String NgayChieu = cbb_ngaychieu.getSelectedItem().toString();
        String LoaiPhim = cbb_loaiphim.getSelectedItem().toString();
        String TenPhim  = cbb_phim.getSelectedItem().toString();
        Vector<String> GioChieu = suatChieu_ctrl.ListThoiGianChieu(NgayChieu, LoaiPhim, TenPhim);
        cbb_giochieu.setModel(new DefaultComboBoxModel<>(GioChieu));
    }
    
    private void HienThiRapPhim(String NgayChieu, String TenPhim, String GioChieu, JLabel label){
        Connection con = JDBCConnection.getJDBCConnection();
        String MaRap = null;
        String sql = "Select marap from suatchieu sc  join phim p on sc.MAPHIM = p.MAPHIM Where ngaychieu = TO_DATE(?,'DD-MM-YYYY') "
                    + "and tenphim = ? and thoigianchieu = ?";
//          String sql = "select  marap from suatchieu sc join phim p on sc.MAPHIM= p.MAPHIM where thoigianchieu = ? "
//                    + "and ngaychieu = TO_DATE(?,'DD-MM-YYYY')"
//                    + " and tenphim = ? ";
        String Rap = null;
        try {
            PreparedStatement prest = con.prepareStatement(sql);
            prest.setString(1, NgayChieu);
            prest.setString(2, TenPhim);
            prest.setString(3, GioChieu);
            ResultSet rs = prest.executeQuery();
            if(rs.next()){
                MaRap = rs.getString(1);
            }
            switch(MaRap){
                case "1r":
                    Rap = "Rạp 1"; break;
                case "2r":
                    Rap = "Rạp 2"; break;
                case "3r":
                    Rap = "Rạp 3"; break;
                case "4r":
                    Rap = "Rạp 4"; break;    
                case "5r":
                    Rap = "Rạp 5"; break;  
            }
            label.setText(Rap);
             DatVe.MaRap = MaRap;   
        } catch (SQLException ex) {
            Logger.getLogger(DatVe.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(DatVe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void GheDaChon(JToggleButton a) {
        if(a.isSelected()){
            a.setBackground(new Color(102,102,102));
            // hiển thị ghế đã chọn bên lable ghế
            String str = label_ghe_ve.getText() + " " + a.getText();
            label_ghe_ve.setText(str);
            // hiển thị giá vé bên lable giá vé
            long giave = Long.parseLong(label_gia_ve.getText()) + 45000;
            label_gia_ve.setText(String.valueOf(giave));
            
            String maghe = a.getText().toLowerCase();
            String i =  MaRap.substring(0,1); // vi du 1r -> i = 1
            String j =  MaRap.substring(1); // j=r
            String marap = j + i;
            maghe = maghe + marap;
            MaGhe.add(maghe);
        }
        else{
            a.setBackground(UIManager.getColor("Button.background"));//đưa về màu mặc định khi ko chọn
            String str = label_ghe_ve.getText().replace(" " + a.getText(),"");
            label_ghe_ve.setText(str);
            long giave = Long.parseLong(label_gia_ve.getText()) - 45000;
            label_gia_ve.setText(String.valueOf(giave));
            
            String maghe = a.getText().toLowerCase();
            String i =  MaRap.substring(0,1); // vi du 1r -> i = 1
            String j =  MaRap.substring(1); // j=r
            String marap = j + i;
            maghe = maghe + marap;
            MaGhe.remove(maghe);
        }
        
    }
    public  static String tenghe;
}


    

